model_params:
  net_type: 'resnet' # resnet/densenet/lenet
  dataset_list: ['cifar10']
  out_dist_list: ['svhn', 'imagenet_resize', 'lsun_resize', 'subset_cifar100']
  num_train: 1000 # 1000 for 'svhn', 'imagenet_resize', 'lsun_resize', 50*num of  OOD classes in subset_cifar100
  partition: 2000 # req for cifar100_subset datasets

exp_params:
  score_list: ['Ensembled_0.0_10','Ensembled_0.0_20','Ensembled_0.0_30','Ensembled_0.0_40','Ensembled_0.0_50']

logging_params:
  outf: 'test'
  output_file: 'cifar10_resnet34' # for running parallel experiments
  exp_display_name: 'cifar10_resnet34' # for saving the results of parallel experiments
